### PR TITLE
Add PHP Lint

### LINKED ISSUE #11: Add php lint support
Should be able to run basic PHP linting, then have the results sent back to the client (via GH review).

Probably needs a little refactoring of phpcs-scan.php to move the reporting functionality into a more standalone process that can handle N different tasks.

### PR DESCRIPTION
**Pull request by nickdaugherty**
Adding PHP linting support

WORK IN PROGRESS

cc @gudmdharalds 

Fixes #11

### CODE REVIEW

**Comment by nickdaugherty** [comment]
This adds `vipgoci_lint_do_scan()` - the next step is to

**Comment by nickdaugherty** [comment]
Oops wrong button 😆

**Comment by nickdaugherty** [comment]
@gudmdharalds I've added a lint function and refactored a bit to move the main command into `vip-go-ci.php` (has same CLI args as before).

I put a few TODOs in there - the next steps are extracting the GH commenting / reviewing logic into a reusable function, and incorporating that into `vip-go-ci.php`. 

You'll note I [set it up](https://github.com/Automattic/vip-go-ci/pull/12/files#diff-daf19feb4bb02b4eeba6bf5265591a47R100) to support N number of scans - each scan should return an array of results, then they get stored into `$results`. Then, we need the GH code to loop over that and post each result to GH. In the case of lint, the string it returns is acceptable for sending to GH as is...for PHPCS and the inline comments, it'll need another step there.

Is the GH refactoring something you can do? If we can get it sending the lint results as a review (and blocked if there are lint errors), I think we're doing pretty good. Then once we figure out the PHPCS line numbers issue we discussed.

**Comment by nickdaugherty** [comment]
Also we need to figure out the checkout stuff - we can use the TC checkout, we just need to figure out how it works (vs doing our own checkout).

**Comment by nickdaugherty** [comment]
Another thing, we need to fail the build (return a non `0` value from the ci script) if lint errors are found, so that TeamCity sees a failure and marks it as such.

**Comment by gudmdharalds** [comment]
Excellent! I will refactor and have a look at the TODOs :-) 

Thanks for working on this!

**Pull request merged**
