### PR TITLE
Add support for WPScan API scanning

### PR DESCRIPTION
**Pull request by gudmdharalds**
This patch will introduce [WPScan API](https://wpscan.com/api) support to `vip-go-ci` as an optional feature. With the feature set up and enabled, new or altered plugins and themes submitted in pull requests will be scanned for security vulnerabilities using the WPScan API. 

TODO:
  - [x] Specify options parameters to make WPScan API support configurable.
    - [x] Parameter to enable or disable WPScan API support (`--wpscan-api`).
    - [x] Parameter to enable or disable WPScan API dry-run mode (`--wpscan-api-dry-mode`).
    - [x] Parameter to specify directories to scan (`--wpscan-api-paths`).
    - [x] Parameter to specify directories to skip (`--wpscan-api-skip-folders`).
    - [x] Parameter to specify WPScan API URL (`--wpscan-api-url`).
    - [x] Parameter to specify WPScan API access-token (`--wpscan-api-token`).
    - [x] Add test for `vipgoci_run_init_options_wpscan()`.
- [x] Logic to find plugins/themes, determine slugs, and collect vulnerable/obsolete plugins or themes via WPScan API:
  - [x] Logic to determine directories to scan using parameters (`vipgoci_wpscan_find_addon_dirs_altered()`).
     - [x] Add integration test for function
        - [x] Check for themes.
        - [x] Ensure added plugins/themes are included in results.
        - [x] Ensure updated plugins/themes are included in results.
        - [x] Ensure deleted plugins/themes are not included in results.
  - [x] Determine `slug` of plugins or themes altered and get additional data using functionality from WordPress Core (using logic in `wp-core-misc.php`), check for security problems via WPScan API (using logic implemented in `wpscan-api.php`), filter security problems that are not applicable (logic from same file). Make a distinction between vulnerable plugins and obsolete ones (`vipgoci_wpscan_scan_dirs_altered()`).
     - [x] Add integration test for function
       - [x] Add check for themes
  - [x] Save results of WPScan API scanning in results structure (`vipgoci_wpscan_scan_save_for_submission()`)
     - [x] Look for label so end-users can request skip scanning (`skip-wpscan-scan`)
     - [x] Different severity level for obsolete addons (`7`) and vulnerable ones (`10`).
     - [x] Add integration test for function
     - [x] Add test for themes
  - [x] Add function wrapper for a) finding plugins/themes to scan, b) to scan these via WPScan API, c) and save results for submission (`vipgoci_wpscan_scan_commit()`).
    - [x] Add integration test for function
    - [x] Add test for themes
- [x] WPScan result submission logic:
  - [x] Make reporting of generic comments modular, depending on result type (PHP lint or WPScan).
  - [x] Function to output beginning of PHP lint report comment (`vipgoci_lint_report_comment_start()`)
  - [x] Function to output main body of PHP lint report comment  based on results (`vipgoci_lint_report_comment_format_result()`)
  - [x] Report WPScan API results to IRC only if dry-run is enabled.
  - [x] Function to output beginning of WPScan report comment (`vipgoci_wpscan_report_start()`)
    - [x] Integrate into `vipgoci_report_submit_pr_generic_comment_from_results()`
    - [x] Make a distinction between submitting plugin or theme results
    - [x] Add test for function
  - [x] Function to output end of WPScan report comment (`vipgoci_wpscan_report_end()`
    - [x] Make a distinction between submitting plugin or theme results
    - [x] Integrate into `vipgoci_report_submit_pr_generic_comment_from_results()`
    - [x] Add test for function
  - [x] Function that outputs CVSS ranking in human readable form (`vipgoci_wpscan_report_format_cvss_score()`)
    - [x] Implement function, ensure it is called from result formatting function
    - [x] Add unit test for function
  - [x] Function that outputs main body of WPScan report comment based on results (`vipgoci_wpscan_report_comment_format_result()`)
    - [x] Make a distinction between submitting plugin or theme results
    - [x] Integrate into `vipgoci_report_submit_pr_generic_comment_from_results()`
    - [x] Add test for function
- [x] WPScan API scanning support:
  - [x] Function to ask WPScan API for information about individual plugins/themes.
     - [x] Test for `vipgoci_wpscan_do_scan_via_api()`
  - [x] Function to filter away vulnerabilities that do not affect the current plugin/theme version.
    - [x] Test for `vipgoci_wpscan_filter_fixed_vulnerabilities()`
- [x] WordPress Core functionality:
  - [x] Function to retrieve WordPress plugin/theme headers (`vipgoci_wpcore_misc_get_file_wp_headers()`)
    - [x] Add test for `vipgoci_wpcore_misc_get_file_wp_headers()`
    - [x] Function to clean up headers (`vipgoci_wpcore_misc_cleanup_header_comment()`).
       - [x] Add test for `vipgoci_wpcore_misc_cleanup_header_comment()`
  - [x] Function to determine if a file belongs to a theme or a plugin and retrieve headers (`vipgoci_wpcore_misc_get_addon_headers_and_type()`).
    - [x] Add test for `vipgoci_wpcore_misc_get_addon_headers_and_type()`
  - [x] Function to retrieve list of plugins or themes found in a particular directory (`vipgoci_wpcore_misc_scan_directory_for_addons()`)
    - [x] Add test for `vipgoci_wpcore_misc_scan_directory_for_addons()`
    - [x] If `UpdateURI` header found is outside of valid WordPress.org URIs, skip addon.
  - [x] Function to determine slugs for plugins or themes (`vipgoci_wpcore_api_determine_slug_and_other_for_addons()`)
    - [x] Add test for `vipgoci_wpcore_api_determine_slug_and_other_for_addons()`
    - [x] Use HTTP 1.1 for requests.
    - [x] Add theme to integration test.
  - [x] Function to merge fields from WordPress.org API response into array of addons found, plus verification of essential fields (`vipgoci_wpcore_misc_assign_addon_fields()`).
    - [x] Add test for function.
  - [x] Function to get plugin and theme header data, and determine slugs for the plugins/themes and get other information using the WordPress.org API (`vipgoci_wpcore_misc_get_addon_data_and_slugs_for_directory()`)
    - [x] Add test for `vipgoci_wpcore_misc_get_addon_data_and_slugs_for_directory()`
      - [x] Test theme as well.
- [x] Functions that need refining:
  - [x] Refine `vipgoci_http_api_fetch_url()`:
    - [x] Add support for WPScan API access tokens
  - [x] Refine `vipgoci_http_api_post_url()`:
    - [x] Support encoding HTTP POST request postfields using URL-encoded query-strings.
    - [x] Support setting which HTTP protocol version to use for requests.
    - [x] Make access token an optional parameter.
    - [x] Allow callers to specify HTTP `Content-Type` header.
    - [x] Support returning content from API backend.
  - [x] Refine `vipgoci_scandir_git_repo()`:
    - [x] Parameter to disable subdirectory scanning
      - [x] Update integration test so that this parameter is tested.
- [x] Support functions:
  - [x] `vipgoci_preview_string()`: Function to shorten strings, especially useful for logging API responses.
    - [x] Test for `vipgoci_preview_string()`
  - [x] `vipgoci_array_push_uniquely()` Function add items to array, only if they are not in the array already.
    - [x] Test for `vipgoci_array_push_uniquely()`
  - [x] `vipgoci_directory_path_get_dir_and_include_base()`: Function to get "base" path of target directory along with the directory-name itself, skip any sub-directories.
     - [x] Test for `vipgoci_directory_path_get_dir_and_include_base()` 
  - [x] `vipgoci_github_files_affected_by_commit()`: Function to get files affected by each pull request implicated by the commit.
     - [x] Test for `vipgoci_github_files_affected_by_commit()`.
  - [x] `vipgoci_directory_found_in_file_list()`: Function to check if a particular directory path is found in array of file paths.
    - [x] Test for `vipgoci_directory_found_in_file_list()`
  - [x] `vipgoci_string_found_in_substrings_array()`: Check if any of the strings in a given array are a substring of comparison string.
    - [x] Test for `vipgoci_string_found_in_substrings_array()`
  - [x] `vipgoci_output_sanitize_url()`: Function to escape URLs.
    - [x] Add unit test.
  - [x] `vipgoci_output_markdown_escape()`: Function to escape Markdown characters.
    - [x] Add unit test.
- [x] Auto-approval changes:
   - [x] Do not auto-approve if WPScan API finds issues (only when dry-run is disabled).
      - [x] Add integration test for when WPScan indicates issues and when it does not.
- [x] Verify all tests have been added or updated -- both unit and integrated
- [x] Add section about WPScan API support to `--help` message.
- [x] Add section about WPScan API support to README file.
- [x] Add details about WPScan API to `Scan run detail`
  - [x] Add tests also (`unit/tests/ReportCreateScanDetailsWpscanConfigurationTest.php`)
- [x] Add WPScan API TODO item to .github/PULL_REQUEST_TEMPLATE
- [x] Changelog entry [ #286 ]
- [x] Check status of automated tests

### CODE REVIEW

**Comment by iamchughmayank** [comment]
I wonder if the "VIP Code Analysis Bot" checks can be performed as a pre-push step to ensure it passes in the pipeline as well?

**Comment by gudmdharalds** [comment]
> I wonder if the "VIP Code Analysis Bot" checks can be performed as a pre-push step to ensure it passes in the pipeline as well?

I think that should be possible. Let's discuss during our next team meeting.

**Review by nickdaugherty — CHANGES_REQUESTED** [review]
This looks pretty good ... I reviewed it from a security POV and here are my thoughts (avoided inline comments since GH doesn't render the large diffs):

- Avoid passing the WPScan API url through so many layers / args, if possible (maybe use the existing VIPGOCI_WPSCAN_API_BASE_URL instead?). This reduces opportunities for it to get changed to something unexpected: https://github.com/Automattic/vip-go-ci/blob/1349583363d0bbb78236fb6986f258467ad9ac47/wpscan-api.php#L24
- When finding slugs for themes/plugins, we should validate the format early and skip + log if it doesn't match an expected slug format (probably alphanumeric and hyphens?)…this avoids letting malicious payloads into the lower levels
- Does vipgoci_wpscan_report_end() need html escaping similar to vipgoci_wpscan_report_start()? https://github.com/Automattic/vip-go-ci/blob/a8d73957c461b9ce8d30ae42f8596fefa1c6f8a6/wpscan-reports.php#L85
- This unencoded path + filename seems risky…can we do something to escape this in the url? Maybe store the dir + pathname separately, then sanitize each? I can imagine dir/file names with special chars that wouldn't get encoded properly and could alter the url: https://github.com/Automattic/vip-go-ci/blob/a8d73957c461b9ce8d30ae42f8596fefa1c6f8a6/wpscan-reports.php#L190
- Let's escape the vulnerability item id here … it comes from an external source that shouldn't be trusted implicitly: https://github.com/Automattic/vip-go-ci/blob/a8d73957c461b9ce8d30ae42f8596fefa1c6f8a6/wpscan-reports.php#L205
- Are the GH comments we're generating HTML, Markdown, or both? We have a lot of html escaping happening, but this won't prevent markdown injection (injecting links by adding ()[] characters, for example). We need to escape special markdown characters from dynamic values: https://tech.saigonist.com/b/code/escaping-special-characters-markdown.html, https://wilsonmar.github.io/markdown-text-for-github-from-html/#special-characters

**Comment by gudmdharalds** [comment]
In relation to [review](https://github.com/Automattic/vip-go-ci/pull/273/#pullrequestreview-1117525773):

> When finding slugs for themes/plugins, we should validate the format early and skip + log if it doesn't match an expected slug format (probably alphanumeric and hyphens?)…this avoids letting malicious payloads into the lower levels

Resolved in 1d0d93632f66b3595d1728975e30167393a68f0b and 08f0cdebd29d769e5f1f4712465eb71fdc772117 (test: 3f3105bd026a68369c09b400a39e9b88d26bce3a).

***

> Let's escape the vulnerability item id here … it comes from an external source that shouldn't be trusted implicitly: 

https://github.com/Automattic/vip-go-ci/blob/a8d73957c461b9ce8d30ae42f8596fefa1c6f8a6/wpscan-reports.php#L205

Resolved in e3eaafe26046e18bce66edefe09b2967a9438287 (test: a1973a3a2725f2fddff37bc550ef1b805ebbd40b). 

***

> Does vipgoci_wpscan_report_end() need html escaping similar to vipgoci_wpscan_report_start()? 

https://github.com/Automattic/vip-go-ci/blob/a8d73957c461b9ce8d30ae42f8596fefa1c6f8a6/wpscan-reports.php#L85

The whole output is escaped:

https://github.com/Automattic/vip-go-ci/blob/a1973a3a2725f2fddff37bc550ef1b805ebbd40b/wpscan-reports.php#L81

***


> Avoid passing the WPScan API url through so many layers / args, if possible (maybe use the existing VIPGOCI_WPSCAN_API_BASE_URL instead?). This reduces opportunities for it to get changed to something unexpected

https://github.com/Automattic/vip-go-ci/blob/1349583363d0bbb78236fb6986f258467ad9ac47/wpscan-api.php#L24

Resolved in dc652edc2ede7da366abaa484cdbfd4e26213b2c...cf1088dd987171848765b5708bcaaa694edeb0cf.

***

> Are the GH comments we're generating HTML, Markdown, or both? We have a lot of html escaping happening, but this won't prevent markdown injection (injecting links by adding ()[] characters, for example). We need to escape special markdown characters from dynamic values: https://tech.saigonist.com/b/code/escaping-special-characters-markdown.html, https://wilsonmar.github.io/markdown-text-for-github-from-html/#special-characters

This is resolved in 8622e8c68d084f3e07ec014c2b632cb521ba2d38...3f7d8b084aaadf1ab134de78e16796c0270ff204

**Comment by nickdaugherty** [comment]
@gudmdharalds the changes all look good, but do you know if the Markdown escaping is going to come through with a  `\` in the GH comments? Not all characters _always_ need escaping...the position of them is relevant in Markdown. 

An asterisk in the middle of a sentence won't have any effect, but if it starts a line and is followed by a space, it would get turned into a bullet item, for example.

I guess we can see how it works in practice and tweak it if needed.

**Pull request merged**
