### PR TITLE
Updating WP-Coding-Standards to version 2.3.0

### PR DESCRIPTION
**Pull request by gudmdharalds**
See #96.

### CODE REVIEW

**Comment by gudmdharalds** [comment]
@GaryJones: Do we maybe have update [VIP-Coding-Standards](https://github.com/Automattic/VIP-Coding-Standards/) as well?

I discovered this when the unit-tests were run:

>                  'message' => 'The "WordPress.WP.TimezoneChange" sniff has been deprecated. Use the "WordPress.DateTime.RestrictedFunctions" sniff instead. Please update your custom ruleset.'
>                  'source' => 'WordPress.WP.TimezoneChange.DeprecatedSniff'

You can see this in the output from the unit-tests, [here](https://app.circleci.com/pipelines/github/Automattic/vip-go-ci/179/workflows/95815ee3-76b0-47dd-b181-59feda7c7ac3/jobs/200/steps).

**Comment by gudmdharalds** [comment]
I was able to replicate this locally, using this [file](https://raw.githubusercontent.com/Automattic/vip-go-ci-testing/9882d7da670f8f45f3431e3c7da80a00d6af4b5e/my-test-file-1.php), and latest version of `VIP-Coding-Standards`:

```
FILE: /tmp/my-test-file-1.php
---------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AND 1 WARNING AFFECTING 4 LINES
---------------------------------------------------------------------------------------------------------------------------------
  1 | WARNING | The "WordPress.WP.TimezoneChange" sniff has been deprecated. Use the "WordPress.DateTime.RestrictedFunctions"
    |         | sniff instead. Please update your custom ruleset.
...
```

I can see though that the sniff has been removed from the [develop branch](https://github.com/Automattic/VIP-Coding-Standards/compare/2.0.0...develop#diff-f5dc5af119bdbcaab28af5fb8cdcaad0L29).
```

**Comment by GaryJones** [comment]
@gudmdharalds A compatible version of VIPCS has not yet been released that addresses this.

**Comment by gudmdharalds** [comment]
@GaryJones: I think this change will need to wait until a new release is made of VIPCS that fixes this. 

Do you know when a new release will be made?

**Comment by GaryJones** [comment]
When I get to it - I can aim for next week.

**Comment by GaryJones** [comment]
Closing in favour of #106, which not only bumps WPCS to 2.3.0, but also updates VIPCS to 2.1.0 (which addresses the TimezoneChange issue).

**Pull request closed without merging**
